[project]
name = "lakehouse"
version = "0.1.0"
description = "lakehouse project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml"
]

[tool.setuptools]
packages = ["lakehouse"]
package-dir = {"" = "src"}
